In [2]:
# Import pandas and load the data

import pandas as pd

# Load the cleaned loan applications data directly from the Excel file
df = pd.read_excel(r"C:\Users\suraj\OneDrive\Desktop\Projects\Cap_Project_5\Cleaned dataset\loan_applications_cleaned.xlsx")

In [3]:
# Look at the first few rows
df.head()

,Applicant_ID,Applicant_Name,Gender,Age,Marital_Status,Branch_ID,Employment_Type,Annual_Income_INR,Credit_Score,Existing_Loans_Count,...,Interest_Rate_Percent,EMI_Monthly_INR,Debt_to_Income_Ratio,Collateral_Value_INR,Late_Payments_Past_Count,Application_Date,Loan_Status,Default_Flag,Default_Date,Days_Past_Due
0,LN000001,Rajesh Patel,Male,45.0,Single,BR015,Self-Employed,528100.0,733.0,0,...,0.0867,20110.80,0.46,2912000,1,2024-09-06,Approved,No,NaT,0
1,LN000002,Krishna Patel,Male,32.0,Single,BR017,Salaried,780600.0,653.0,0,...,0.1297,10012.97,0.15,686900,0,2022-02-17,Approved,No,NaT,0
2,LN000003,Aditya Chauhan,Male,24.0,Single,BR003,Salaried,442500.0,807.0,2,...,0.1143,8822.15,0.49,557300,0,2023-05-24,Approved,Yes,2023-11-19,18
3,LN000004,Neha Iyer,Female,NaN,Single,BR001,Business Owner,290300.0,779.0,0,...,0.0821,0.00,0.71,1579200,0,2024-03-24,Rejected,No,NaT,0
4,LN000005,Reyansh Mehta,Male,30.0,Single,BR016,Salaried,527900.0,701.0,0,...,0.1099,4219.38,0.10,0,0,2024-10-02,Approved,No,NaT,0

In [4]:
# Check the shape of the data (rows, columns)
df.shape

print(f"The dataset has {df.shape[0]} rows and {df.shape[1]} columns")

The dataset has 5500 rows and 24 columns

In [5]:
# Check column names and data types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Applicant_ID              5500 non-null   object
 1   Applicant_Name            5500 non-null   object
 2   Gender                    5500 non-null   object
 3   Age                       5363 non-null   float64
 4   Marital_Status            5500 non-null   object
 5   Branch_ID                 5500 non-null   object
 6   Employment_Type           5500 non-null   object
 7   Annual_Income_INR         5390 non-null   float64
 8   Credit_Score              5418 non-null   float64
 9   Existing_Loans_Count      5500 non-null   int64
 10  Existing_EMI_Monthly_INR  5500 non-null   float64
 11  Loan_Purpose              5500 non-null   object
 12  Loan_Amount_INR           5500 non-null   int64
 13  Loan_Tenure_Months        5500 non-null   int64
 14  Interest_Rate_Percent     5500 non-null   float64
 15  EMI_Monthly_INR           5500 non-null   float64
 16  Debt_to_Income_Ratio      5500 non-null   float64
 17  Collateral_Value_INR      5500 non-null   int64
 18  Late_Payments_Past_Count  5500 non-null   int64
 19  Application_Date          5500 non-null   datetime64[ns]
 20  Loan_Status               5500 non-null   object
 21  Default_Flag              5500 non-null   object
 22  Default_Date              749 non-null    datetime64[ns]
 23  Days_Past_Due             5500 non-null   int64
dtypes: datetime64[ns](2), float64(7), int64(6), object(9)
memory usage: 1.0+ MB

In [9]:
# Summary statistics for numeric columns

df.describe()

,Age,Annual_Income_INR,Credit_Score,Existing_Loans_Count,Existing_EMI_Monthly_INR,Loan_Amount_INR,Loan_Tenure_Months,Interest_Rate_Percent,EMI_Monthly_INR,Debt_to_Income_Ratio,Collateral_Value_INR,Late_Payments_Past_Count,Application_Date,Default_Date,Days_Past_Due
count,5363.000000,5.390000e+03,5418.000000,5500.000000,5500.000000,5.500000e+03,5500.000000,5500.000000,5500.000000,5500.000000,5.500000e+03,5500.000000,5500,749,5500.000000
mean,36.102182,5.018543e+05,677.319860,0.802000,2927.845035,7.910793e+05,82.831636,0.115209,9669.645122,0.399807,7.301352e+05,0.724727,2023-12-26 04:55:35.563636480,2024-11-03 03:56:28.518024192,8.599091
min,21.000000,9.000000e+04,333.000000,0.000000,0.000000,2.500000e+04,6.000000,0.070000,0.000000,0.030000,0.000000e+00,0.000000,2022-01-01 00:00:00,2022-02-27 00:00:00,0.000000
25%,29.000000,2.964250e+05,615.000000,0.000000,0.000000,1.491750e+05,36.000000,0.097000,0.000000,0.210000,0.000000e+00,0.000000,2022-12-31 18:00:00,2024-02-26 00:00:00,0.000000
50%,36.000000,4.356500e+05,677.000000,1.000000,758.540000,3.312500e+05,48.000000,0.111600,5399.155000,0.350000,0.000000e+00,0.000000,2023-12-30 00:00:00,2025-01-27 00:00:00,0.000000
75%,43.000000,6.179000e+05,742.000000,1.000000,4634.055000,9.069750e+05,120.000000,0.134500,13600.455000,0.550000,9.800500e+05,1.000000,2024-12-29 00:00:00,2025-09-02 00:00:00,0.000000
max,65.000000,4.369800e+06,900.000000,6.000000,57937.810000,4.370550e+07,300.000000,0.171600,310600.660000,1.610000,1.406130e+07,6.000000,2025-12-30 00:00:00,2025-12-30 00:00:00,359.000000
std,9.501369,3.184834e+05,94.038573,0.886276,4458.462685,1.345494e+06,79.624670,0.021819,13925.736391,0.241692,1.377032e+06,0.913741,NaN,NaN,31.107563

In [11]:
# Check for missing (null) values in each column

df.isnull().sum()

Applicant_ID                   0
Applicant_Name                 0
Gender                         0
Age                          137
Marital_Status                 0
Branch_ID                      0
Employment_Type                0
Annual_Income_INR            110
Credit_Score                  82
Existing_Loans_Count           0
Existing_EMI_Monthly_INR       0
Loan_Purpose                   0
Loan_Amount_INR                0
Loan_Tenure_Months             0
Interest_Rate_Percent          0
EMI_Monthly_INR                0
Debt_to_Income_Ratio           0
Collateral_Value_INR           0
Late_Payments_Past_Count       0
Application_Date               0
Loan_Status                    0
Default_Flag                   0
Default_Date                4751
Days_Past_Due                  0
dtype: int64